brewTrack/bar/urls.py
from django.conf.urls import url
from .views import *

from . import views

app_name = 'bar'
urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^register', Register.as_view(), name='register'),
    url(r'^login', Login.as_view(), name='login'),
    url(r'^logout', views.logout_view, name="logout"),
    url(r'^user/profile/$', Profile.as_view(), name='profile'),
    url(r'^bar/(?P<pk>[0-9]+)/$', BarPage.as_view(), name='bar'),
    url(r'^bar/create/$', CreateBarPage.as_view(), name='create_bar'),
    url(r'^bar/(?P<pk>[0-9]+)/edit_bar/$', UpdateBarPage.as_view(), name='update_bar'),
    url(r'^bar/(?P<pk>[0-9]+)/delete_bar/$', DeleteBarPage.as_view(), name='delete_bar'),

    # Item CRUD
    url(r'^bar/(?P<pk>[0-9]+)/create_item/$', CreateItemPage.as_view(), name='create_item'),
    url(r'^item/(?P<pk>[0-9]+)/edit_item/$', UpdateItemPage.as_view(), name='update_item'),
    url(r'^item/(?P<pk>[0-9]+)/delete_item/$', DeleteItemPage.as_view(), name='delete_item'),
    # Event CRUD
    url(r'^bar/(?P<pk>[0-9]+)/create_event/$', CreateEventPage.as_view(), name='create_event'),
    url(r'^event/(?P<pk>[0-9]+)/edit_event/$', UpdateEventPage.as_view(), name='update_event'),
    url(r'^event/(?P<pk>[0-9]+)/delete_event/$', DeleteEventPage.as_view(), name='delete_event'),
    url(r'^bar/(?P<pk>[0-9]+)/events/$', EventPage.as_view(), name='events'),

    url(r'^bar/(?P<pk>[0-9]+)/next/$', NextBarPage.as_view(), name='next'),
    url(r'^bar/(?P<pk>[0-9]+)/pos/$', PointOfSales.as_view(), name='pos'),
]

brewTrack/brewTrack/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [
    url(r'', include('bar.urls')),
    url(r'^admin/', admin.site.urls),
]

brewTrack/bar/forms.py
from django.contrib.auth.models import User
from .models import *
from django import forms

class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'uk-input','placeholder' : 'username',}))
    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'uk-input','placeholder' : 'email',}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'uk-input','placeholder' : 'password',}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password', ]


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'uk-input ','placeholder' : 'username',}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'uk-input ','placeholder' : 'password',}))

    class Meta:
        model = User
        fields = ['username', 'password']

class BarForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.fields['location'].label = "Address"

    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Name of Bar',}))
    location = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Full Address',}))
    hours = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Ex. 5pm-2am',}))

    class Meta:
        model = Bar
        fields = ['name', 'location', 'hours']


class ItemForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)
          self.fields['total_amount'].label = "Keg Size (oz)"
          self.fields['size'].label = "Size (oz)"
          self.fields['amount_flag'].label = "Is There A Keg?"
          self.fields['location'].label = "Brewery Locaion"

    name = forms.CharField(widget=forms.TextInput(attrs={
        'id':'drink-name','class': 'uk-input ','placeholder' : 'Bud Light, Vodka Cranberry, Yuengling Lager, ...',}))
    size = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'uk-input ','placeholder' : '12, 16, 24, ...',}))
    price = forms.DecimalField(
        max_digits=5, decimal_places=2, widget=forms.NumberInput(attrs={
        'class': 'uk-input ','placeholder' : 'Price of Drink ($)',}))
    type = forms.ChoiceField(
        choices=[('Beer','Beer'),('Cocktail','Cocktail'),('Wine','Wine')], widget=forms.Select(attrs={
        'id':'type-value','class':'uk-select',}))
    subtype = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'IPA, Vodka, Lager, Whiskey, ...',}))
    amount_flag = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={
        'class': 'uk-checkbox text-check',}))
    total_amount = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={
        'class': 'uk-input ','placeholder' : 'Total ounces of the keg (generally 1980 oz.)'}))
    location = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Philadelphia PA, Athens GA, ...',}))
    alcholic_content = forms.DecimalField(
        required=False, max_digits=5, decimal_places=2, widget=forms.NumberInput(attrs={
        'class': 'uk-input ','placeholder' : 'ABV',}))

    class Meta:
        model = Item
        fields = ['name', 'size', 'price', 'type', 'subtype', 'amount_flag', 'total_amount', 'location', 'alcholic_content']

class EventForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)

    name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Name of Event',}))
    type = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Band, Preformance, Special, etc.',}))
    description = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Band, Preformance, Special, etc.',}))
    date = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'id':'datepicker','class': 'uk-input','type':"text",'placeholder' : 'Event Date',}))
    reoccuring_flag = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={
        'class': 'uk-checkbox text-check',}))
    frequancy = forms.CharField(required=False, widget=forms.TextInput(attrs={
        'class': 'uk-input ','placeholder' : 'Sample: M 9pm-10pm, Th 10pm-2am',}))
    ticket_flag = forms.BooleanField(
        required=False, widget=forms.CheckboxInput(attrs={
        'class': 'uk-checkbox text-check',}))

    class Meta:
        model = Event
        fields = ['name', 'type', 'description', 'reoccuring_flag', 'frequancy', 'ticket_flag', 'date']

class PayForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
          super().__init__(*args, **kwargs)

    class Meta:
        model = Item
        fields = ['current_amount', 'purchases']

brewTrack/bar/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, DetailView, TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.contrib.auth import authenticate, login, logout
from bar.forms import *
from .models import *
import datetime
import json

class Index(ListView):
    model = Bar
    # Ordering Alphabetically
    ordering = ['name']
    template_name = 'bar/index.html'

# Kept this a Functinon based view for simplicity
def logout_view(request):
    logout(request)
    return redirect('/')

class Profile(ListView):
    model = Bar
    # Ordering Alphabetically
    ordering = ['name']
    template_name = 'bar/profile.html'

class CreateBarPage(CreateView):
    model = Bar
    form_class = BarForm
    template_name = 'bar/event_form.html'

    def form_valid(self, form):
        bar = form.save(commit=False)
        bar.pub_date = datetime.datetime.today().strftime('%Y-%m-%d')
        bar.save()
        menu = Menu.objects.create(name=bar.name + " Menu", bar=bar)

        # TODO: Change to redirct to last page
        return redirect('/')

class UpdateBarPage(UpdateView):
    model = Bar
    form_class = BarForm
    template_name = 'bar/event_form.html'

    def form_valid(self, form):
       form.save()
       # TODO: Change to redirct to last page
       return redirect('/')

class DeleteBarPage(DeleteView):
    model = Bar
    # TODO: Change to redirct to last pagef
    success_url = reverse_lazy('bar:index')

# Bar Page and Form
class BarPage(DetailView):
    template_name = 'bar/bar_page.html'
    model = Bar

    def get_context_data(self, **kwargs):
        pk = self.kwargs['pk']
        context = super(BarPage, self).get_context_data(**kwargs)
        bar = get_object_or_404(Bar, pk=pk)
        menu = Menu.objects.get(bar=pk)
        items = Item.objects.filter(menu=menu.id).order_by('name')
        events = Event.objects.filter(bar=pk).order_by('date')[:3]

        typeList = {}
        subList = {}
        for item in items:
          if item.type not in typeList:
              typeList[item.type] = item.type
          if item.subtype not in subList:
             subList[item.subtype] = item.subtype

        context = {
            'bar' : bar,
            'menu' : menu,
            'events': events,
            'menuList' : items,
            'typeList' : typeList,
            'subList' : sorted(subList)
        }

        return context

# CRUD for Item
class CreateItemPage(CreateView):
    form_class = ItemForm
    template_name = 'bar/item_form.html'

    def get_context_data(self, **kwargs):
       context = super(CreateItemPage, self).get_context_data(**kwargs)
       pk = self.kwargs['pk']
       bar = Bar.objects.get(pk=pk)
       menu = Menu.objects.get(bar=pk)
       context['bar'] = bar
       context['menu'] = menu
       return context

    def form_valid(self, form):
        pk = self.kwargs['pk']
        menu = Menu.objects.get(bar=pk)
        item = form.save(commit=False)
        item.current_amount = item.total_amount
        item.menu = menu
        item.save()
        return redirect('/bar/' + pk)


class UpdateItemPage(UpdateView):
    model = Item
    form_class = ItemForm
    template_name = 'bar/item_form.html'

    def form_valid(self, form):
       form.save()
       # TODO: Change to redirct to last page
       return redirect('/')

class DeleteItemPage(DeleteView):
    model = Item
    # TODO: Change to redirct to last pagef
    success_url = reverse_lazy('bar:index')

# CRUD Events
class CreateEventPage(CreateView):
    form_class = EventForm
    template_name = 'bar/event_form.html'

    def get_context_data(self, **kwargs):
       context = super(CreateEventPage, self).get_context_data(**kwargs)
       pk = self.kwargs['pk']
       bar = Bar.objects.get(pk=pk)
       context['bar'] = bar
       return context

    def form_valid(self, form):
        pk = self.kwargs['pk']
        bar = Bar.objects.get(pk=pk)
        event = form.save(commit=False)
        event.bar = bar
        event.save()
        return redirect('/bar/' + pk)


class EventPage(ListView):
    model = Bar
    # Ordering Alphabetically
    ordering = ['date']
    template_name = 'bar/events.html'

    def get_context_data(self, **kwargs):
       context = super(EventPage, self).get_context_data(**kwargs)
       pk = self.kwargs['pk']
       bar = Bar.objects.get(pk=pk)
       menu = Menu.objects.get(bar=pk)
       events = Event.objects.filter(bar=bar.id)

       context['events'] = events
       context['bar'] = bar
       return context

class UpdateEventPage(UpdateView):
    model = Event
    form_class = EventForm
    template_name = 'bar/event_form.html'

    def form_valid(self, form):
       form.save()
       # TODO: Change to redirct to last page
       return redirect('/')

class DeleteEventPage(DeleteView):
    model = Event
    # TODO: Change to redirct to last pagef
    success_url = reverse_lazy('bar:index')


class PointOfSales(View):
    model = Bar
    # form_class = PayForm
    template_name = 'bar/pos.html'

    def get(self, request, pk):

        # pk = self.kwargs['pk']
        bar = get_object_or_404(Bar, pk=pk)
        menu = Menu.objects.get(bar=pk)
        items = Item.objects.filter(menu=menu.id).order_by('name')

        typeList = {}
        subList = {}
        for item in items:
          if item.type not in typeList:
              typeList[item.type] = item.type
          if item.subtype not in subList:
             subList[item.subtype] = item.subtype

        context = {
            'bar' : bar,
            'menu' : menu,
            'items' : items,
            'typeList' : typeList,
            'subList' : sorted(subList)
        }
        return render(request, self.template_name, context)

    def post(self, request, pk):
        pk = self.kwargs['pk']
        bar = get_object_or_404(Bar, pk=pk)
        menu = Menu.objects.get(bar=pk)
        items = Item.objects.filter(menu=menu.id).order_by('name')

        typeList = {}
        subList = {}
        for item in items:
          if item.type not in typeList:
              typeList[item.type] = item.type
          if item.subtype not in subList:
             subList[item.subtype] = item.subtype

        context = {
            'bar' : bar,
            'menu' : menu,
            'items' : items,
            'typeList' : typeList,
            'subList' : sorted(subList)
        }

        json_data=json.loads(request.body)

        try:
            for p_item in json_data:
                item = Item.objects.get(pk=p_item['id'])
                if item.current_amount:
                    current_amount = item.current_amount  - (item.size * p_item['count'])
                    Item.objects.filter(pk=p_item['id']).update(current_amount=current_amount)

                purchases = item.purchases + p_item['count']
                Item.objects.filter(pk=p_item['id']).update(purchases=purchases)

        except Exception as error:
            print('Caught this error: ' + repr(error))


        return render(request, self.template_name, context)


class Login(TemplateView):
    template_name = 'bar/login.html'

    def get(self, request):
        form = LoginForm()
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/')

        return render(request, self.template_name, {'form' : form})

class Register(TemplateView):
    template_name = 'bar/register.html'

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template_name, {'form' : form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('/')

        return render(request, self.template_name, {'form' : form})

# This is a Test Page
class NextBarPage(DetailView):
    model = Bar
    template_name = 'bar/next.html'

    def get_context_data(self, **kwargs):
       context = super(NextBarPage, self).get_context_data(**kwargs)
       return context

brewTrack/bar/templates/bar/bar_page.html
{% extends "bar/base.html" %}
{% block content %}

<h1>{{ bar.name }}</h1>

{% if user.is_authenticated %}
<a class="uk-align-right" href="{% url 'bar:pos' bar.id%}">
<button class="uk-button uk-button-primary">
    Point of Sales
</button></a>
{% endif %}

<p>Welcome to the {{ bar.name }} brewTrack page!</p>

{# Events #}

    <h2>
        Events
        {% if user.is_authenticated %}
        <a id="" uk-icon="cog" href="#events-setting" uk-toggle></a>
        {% endif %}
    </h2>
    {# Events Modal #}

<div id="events-setting" uk-modal>
    <div class="uk-modal-dialog">
        <button class="uk-modal-close-default" type="button" uk-close></button>
        <div class="uk-modal-header">
            <h2 class="uk-modal-title">Event Options</h2>
        </div>
        <div class="uk-modal-footer uk-text-right">
            <a href="{% url 'bar:create_event' bar.id%}">
                <button class="uk-button uk-button-primary" type="button">Add Event</button>
            </a>
            <a href="{% url 'bar:events' bar.id%}">
                <button class="uk-button uk-button-primary" type="button">See All Events</button>
            </a>
        </div>
    </div>
</div>


    <div class=" uk-grid-match uk-grid-small uk-child-width-1-2@s" uk-grid>
        <div class="">
            <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-animation-fade">
                <h3 class="uk-card-title uk-margin-remove-bottom uk-margin-remove-top">Next Event - {{events.first.name}}</h3>
                <p>{{events.first.type}}</p>
                <p>{{events.first.date}}</p>
                <p>{{events.first.description}}</p>

            </div>
        </div>
        <div class="">
            <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-animation-fade">
                <h3 class="uk-card-title uk-margin-remove-bottom uk-margin-remove-top">Upcoming Events</h3>
                {% for event in events %}
                    <p>{{ event.name }} - {{event.date}}</p>
                {% endfor %}
            </div>
        </div>
    </div>


<h2>Menu
    {% if user.is_authenticated %}
    <a id="item-add" uk-icon="plus" href="{% url 'bar:create_item' bar.id %}"></a>
    {% endif %}
</h2>

{# Filter Tabs #}
<div uk-filter="target: .js-filter">
    <div class="uk-grid-small uk-grid-divider uk-child-width-auto" uk-grid>
        <div>
            <ul class="uk-subnav uk-subnav-pill" uk-margin>
                <li class="uk-active" uk-filter-control><a href="#">All</a></li>
            </ul>
        </div>
        <div>
            <ul class="uk-subnav uk-subnav-pill" uk-margin>
                {% for type in typeList %}
                <li uk-filter-control="[data-tags*='{{type}}']"><a href="#">{{type}}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div>
            <ul class="uk-subnav uk-subnav-pill" uk-margin>
                {% for type in subList%}
                <li uk-filter-control="[data-tags*='{{type}}']"><a href="#">{{type}}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>

{# Item Cards #}
    <div class="js-filter uk-grid-match uk-grid-small uk-child-width-1-3@s uk-flex-left" uk-grid>
        {% for item in menuList %}
        <div data-tags="{{item.type}} {{item.subtype}}">
            <div class="uk-card uk-card-default uk-card-hover uk-card-body uk-animation-fade">
                {% if user.is_authenticated %}
                <a class="uk-card-badge" uk-icon="settings" href="#item-settings-{{item.id}}" uk-toggle></a>
                {% endif %}
                <div class="uk-flex uk-flex-middle">
                    <h3 class="uk-card-title uk-margin-remove-bottom">{{item.name}}</h3>
                    <p class="item-size uk-card-title ">{{item.size}} oz.</p>
                </div>

                <div>{{item.subtype}}</div>
                <div>
                    ${{item.price}}
                </div>
                {% if item.location %}
                <div>
                    <span uk-icon="location"></span> {{item.location}}
                </div>
                {% endif %}
                {% if item.amount_flag %}
                <progress class="uk-progress" value="{{item.current_amount}}" min="0" max="{{item.total_amount}}"></progress>
                {% endif %}
            </div>
        </div>

{# Items Setting Modal #}
        <div id="item-settings-{{item.id}}" uk-modal>
            <div class="uk-modal-dialog">
                <button class="uk-modal-close-default" type="button" uk-close></button>
                <div class="uk-modal-header">
                    <h2 class="uk-modal-title">{{item.name}} Settings</h2>
                </div>
                <div class="uk-modal-body uk-card uk-card-body">
                    <div class="">
                        <div class="uk-flex uk-flex-middle">
                            <h3 class="uk-card-titleuk-margin-remove-bottom">{{item.name}}</h3>
                            <p class="item-size uk-card-title ">{{item.size}} oz.</p>
                        </div>
                        <div>{{item.subtype}}</div>
                        <div>${{item.price}}</div>
                        {% if item.location %}
                        <div><span uk-icon="location"></span> {{item.location}}</div>
                        {% endif %}
                        {% if item.amount_flag %}
                        <progress class="uk-progress" value="{{item.current_amount}}" min="0" max="{{item.total_amount}}"></progress>
                        {% endif %}
                    </div>
                </div>
                <div class="uk-modal-footer">
                    <button class="uk-button uk-button-danger uk-align-right" type="button" type="button" uk-toggle="target: #item-delete-{{item.id}}">Delete</button>

                    <a href="{% url 'bar:update_item' item.id%}">
                        <button class="uk-button uk-button-primary uk-align-right" type="button">Edit</button>
                    </a>
                </div>
            </div>
        </div>
{# Are you sure Modal #}
        <div id="item-delete-{{item.id}}" uk-modal>
            <div class="uk-modal-dialog">
                <button class="uk-modal-close-default" type="button" uk-close></button>
                <div class="uk-modal-header">
                    <h2 class="uk-modal-title">Are you sure you want to delete {{item.name}}?</h2>
                </div>
                <div class="uk-modal-footer">
                    <form class="" action="{% url 'bar:delete_item' item.id%}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="item.id" value="{{item.id}}">
                        <button class="uk-button uk-button-danger uk-align-right" href="" type="submit">Delete</button>
                        <button class="uk-button uk-button-default uk-align-right uk-modal-close" type="button" uk-toggle="target: #item-settings-{{item.id}}">Cancel</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script type="text/javascript">

</script>

{% endblock content %}

brewTrack/bar/templates/bar/events.html
{% extends "bar/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <div>
        <div class="uk-card uk-card-default uk-card-body uk-card-hover">
            <div class="uk-card-header">
                <h1 class="uk-card-title uk-margin-remove-bottom">{{bar.name}} Event</h1>
            </div>

            <ul class="uk-list uk-list-divider">
                {% for event in events %}
                <li class="uk-animation-fade">
                    <h3 class="uk-margin-top uk-margin-remove-bottom">
                        {{ event.name }}

                        <form id="delete-event" action="{% url 'bar:delete_event' event.id%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="event.id" value="{{event.id}}">
                            <a class="trash-button uk-align-right" onclick="document.getElementById('delete-event').submit();" uk-icon="trash"></a>
                        </form>
                        <a class="uk-align-right" uk-icon="settings" href="{% url 'bar:update_event' event.id%}"></a>
                    </h3>
                    <div>{{event.type}}</div>
                    <div><span uk-icon="calendar"></span>{{event.date}}</div>
                    <div class="">{{event.description}}</div>
                </li>
                <br />

                {% endfor %}
            </ul>


        </div>
    </div>
    {% else %}
    <h1>Access Denied</h1>
{% endif %}
{% endblock content %}

brewTrack/bar/templates/bar/index.html
{% extends "bar/base.html" %}

{% block content %}
<style>
    #map {
        margin-top: 25px;
        height: 60vh;
        width: 100%;
    }
</style>
<div class="uk-grid-small uk-grid-match uk-child-width-1-2@m" uk-grid>
    <div>
        <div class="uk-card uk-card-default uk-card-body uk-card-hover">
            <div class="uk-card-header">
                <h1 class="uk-card-title uk-margin-remove-bottom">Local Bars</h1>
            </div>

                <div class="scrollable" style="height: 62.5vh;">
                    {% if bar_list %}
                    <ul class="uk-list uk-list-divider">
                        {% for bar in bar_list %}
                        <li class="uk-animation-fade">
                            <h3 class="uk-margin-top">
                                <a href="{% url 'bar:bar' bar.id %}">{{ bar.name }}</a>
                            </h3>
                            <div><span uk-icon="location"></span>{{bar.location}}</div>
                            <div><span uk-icon="calendar"></span>{{bar.hours}}</div>
                        </li>
                        <br />

                        {% endfor %}
                    </ul>
                    {% else %}
                    <p>No bars :(</p>
                    {% endif %}
                </div>
        </div>
    </div>

    <div>
        <div class="uk-card uk-card-default uk-card-body uk-card-hover">
            <div class="uk-card-header">
                <h1 class="uk-card-title">Map</h1>
            </div>
            <div id="map" class="uk-animation-fade"></div>
        </div>
    </div>


</div>

<script src="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"></script>
<link type="text/css" rel="stylesheet" href="https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css"/>

<script>
  barList = []
  L.mapquest.key = 'DRWqawOaON9BhBAg7SLazItfXHWdk9Dq';

  var map = L.mapquest.map('map', {
    center: [40.7934, -77.8600],
    layers: L.mapquest.tileLayer('map'),
    zoom: 16
  });

  {% for bar in bar_list %}
    $.get( "http://www.mapquestapi.com/geocoding/v1/address?key=DRWqawOaON9BhBAg7SLazItfXHWdk9Dq&location=" + "{{bar.location}}", function( data ) {
      barList.push({"name":'{{bar.name}}', "lat": data.results[0].locations[0].latLng.lat, "lng": data.results[0].locations[0].latLng.lng})

      L.mapquest.textMarker([data.results[0].locations[0].latLng.lat, data.results[0].locations[0].latLng.lng], {
      text: '{{bar.name}}',
      position: 'center',
      type: 'marker',
      icon: {
      primaryColor: '#333333',
      secondaryColor: '#333333',
      size: 'sm'
      }
      }).addTo(map);

    });
  {% endfor %}

  </script>

{% endblock content %}

brewTrack/bar/templates/bar/profile.html
{% extends "bar/base.html" %}

{% block content %}
{% if user.is_authenticated %}
    <div>
        <h1>{{user.username}} Profile</h1>
        <div class="uk-card uk-card-default uk-card-body uk-card-hover">
            <div class="uk-card-header">
                <h1 class="uk-card-title uk-margin-remove-bottom">Bar Manager</h1>
            </div>

            <ul class="uk-list uk-list-divider">
                {% for bar in bar_list %}
                <li class="uk-animation-fade">
                    <h3 class="uk-margin-top uk-margin-remove-bottom">
                        {{ bar.name }}
                    <a class="uk-card-badge" uk-icon="plus" href="/bar/create" uk-toggle></a>
                        <form id="delete-bar" action="{% url 'bar:delete_bar' bar.id%}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="bar.id" value="{{bar.id}}">
                            <a class="trash-button uk-align-right" onclick="document.getElementById('delete-bar').submit();" uk-icon="trash"></a>
                        </form>
                        <a class="uk-align-right" uk-icon="settings" href="{% url 'bar:update_bar' bar.id%}"></a>
                    </h3>
                    <div>{{bar.hours}}</div>
                    <div><span uk-icon="calendar"></span>{{bar.location}}</div>
                </li>
                <br />

                {% endfor %}
            </ul>


        </div>
    </div>
    {% else %}
    <h1>Access Denied</h1>
{% endif %}
{% endblock content %}